title: xgy's personal blogs
markdown: kramdown

# for atom feed
author:
  name: xxxgggyyy
  email: 1315691963@qq.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

    #collections_dir: all_collections
    #collections:
    #posts:
    #output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title:output_ext
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
